name: "debug"

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed
  issue_comment:
    types:
      - created
      - edited

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: hmarr/debug-action@v2