name: "wf-pr-test-label"

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-22.04
    if: >
      (github.event.action == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'nig-gpu'))
    steps:
      - run: |
          echo "pr-test-label"
