name: "wf-pr-test-label"

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  issue_comment:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-22.04
    if: >
      (github.event.action == 'issue_comment' &&
      contains(github.event.comment.html_url, '/pull/') &&
      startsWith(github.event.comment.body, '/re-run') &&
      contains(github.event.pull_request.labels.*.name, 'nig-gpu')) ||
      (github.event.action != 'issue_comment' &&
      contains(github.event.pull_request.labels.*.name, 'nig-gpu'))
    steps:
      - run: |
          echo "pr-test-label"
