name: "wf-pr-publish"

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  publish:
    runs-on: ubuntu-22.04
    if: ${{ github.event.pull_request.merged && !contains(github.event.pull_request.labels.*.name, 'nig-gpu') }}
    steps:
      - run: |
          echo "pr-publish"