name: "wf-pr-test-label"

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  issue_comment:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-22.04
    if: contains(github.event.pull_request.labels.*.name, 'nig-gpu')
    steps:
      - uses: hmarr/debug-action@v2
