name: "wf-pr-test-label"

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  debug:
    runs-on: ubuntu-22.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  test:
    runs-on: ubuntu-22.04
    if: >
      (github.event_name == 'pull_request_target' &&
      contains(github.event.pull_request.labels.*.name, 'nig-gpu'))
    steps:
      - run: |
          echo "pr-test-label"
