name: "wf-pr-test"

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  issue_comment:
    types:
      - created

jobs:
  debug:
    runs-on: ubuntu-22.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  test:
    runs-on: ubuntu-22.04
    if: >
      (github.event.action == 'issue_comment' &&
      contains(github.event.comment.html_url, '/pull/') &&
      startsWith(github.event.comment.body, '/re-run')) ||
      (github.event.action == 'pull_request_target' &&
      !contains(github.event.pull_request.labels.*.name, 'nig-gpu'))
    steps:
      - run: |
          echo "pr-test"
